trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd api  # Change to the directory where package.json is located
    npm install
    npm run build
    npx prisma generate  # Run Prisma Client generation
    npx prisma migrate dev  # Run Prisma migrations in development mode
  displayName: 'npm install, build, Prisma generate, and migrate'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'api'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to artifact staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
