trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    cd webapp  # Change to the directory where npm run build is executed
    npm install
    npm run build
  displayName: 'npm install and build in webapp'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'webapp/dist'  # Adjust the path based on the actual location of the dist folder
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to artifact staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
