name: AKS pipeline
on:
  push:
    branches:
      - main
jobs:
  Build-Deploy to AKS:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}
      FRONTEND_IMAGE_NAME: webapp-frontend
      FRONTEND_IMAGE_TAG: V1
      BACKEND_IMAGE_NAME: webapp-backend
      BACKEND_IMAGE_TAG: V1
      CLUSTER_NAME: AKS
      RESOURCE_GROUP: PipelinesAKS
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Build Frontend image
        run: |
          docker built -t $DOCKER_REPOSITORY/FRONTEND_IMAGE_NAME:FRONTEND_IMAGE_TAG ./webapp/Dockerfile ./webapp/
             
      - name: Build backend image
        run: |
          docker built -t $DOCKER_REPOSITORY/BACKEND_IMAGE_NAME:BACKEND_IMAGE_TAG ./api/Dockerfile ./api/    
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: push to the docker registry
        run: |
          docker push $DOCKER_REPOSITORY/FRONTEND_IMAGE_NAME:FRONT_IMAGE_TAG
          docker push $DOCKER_REPOSITORY/BACKEND_IMAGE_NAME:BACKEND_IMAGE_TAG  
          - name: Gets K8s context
        uses: azure/aks-set-context@94ccc775c1997a3fcfbfbce3c459fec87e0ab188
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
      - name: Apply deployment
        run: |
          envsubst < deployment.yaml | kubectl apply -f -

      - name: Apply service
        run: |
          envsubst < service.yaml | kubectl apply -f -
