name: AKS pipeline

on:
  workflow_dispatch:

jobs:
  build_deploy_to_AKS:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: ${{ secrets.DOCKERHUB_USERNAME }}
      FRONTEND_IMAGE_NAME: webapp-frontend
      FRONTEND_IMAGE_TAG: V1
      BACKEND_IMAGE_NAME: webapp-backend
      BACKEND_IMAGE_TAG: V1
      CLUSTER_NAME: AKS
      RESOURCE_GROUP: PipelinesAKS
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Build Frontend image
        run: |
          docker build -t $DOCKER_REPOSITORY/$FRONTEND_IMAGE_NAME:$FRONTEND_IMAGE_TAG ./webapp/

      - name: Build backend image
        run: |
          docker build -t $DOCKER_REPOSITORY/$BACKEND_IMAGE_NAME:$BACKEND_IMAGE_TAG ./api/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Frontend image
        run: docker push $DOCKER_REPOSITORY/$FRONTEND_IMAGE_NAME:$FRONTEND_IMAGE_TAG

      - name: Push Backend image
        run: docker push $DOCKER_REPOSITORY/$BACKEND_IMAGE_NAME:$BACKEND_IMAGE_TAG

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Apply deployment and service
        run: |
         kubectl apply -f $GITHUB_WORKSPACE/Deployment.yaml
         kubectl apply -f $GITHUB_WORKSPACE/service.yaml

